### ISSUE TITLE
Design an alternative to tunnel.endpoints

### ISSUE THREAD

**Issue by cryptix** [ssb-ngi-pointer/go-ssb-room#110]
**Problem:**

muxrpc source `tunnel.endpoints` emits the _full_ list of connected peers for each change in connected peers. This is overhead intensive if people join and leave a lot. It sends n-1 (in case of leave, or n+1 in case of a join) peer identifiers for each connected peer.

Additionally, if an UI want's to do something _nice_ with the list of peers (like who joined or left last) it has to keep the state for comparison anyhow so the _reactive_ argument of not having to hold the state doesn't really count and shouldn't count for a network protocol in any case.

**Solution:**

Just emit state changes in the form of `{type: left, id: @their=.feed}` with valid values for `type`: `joined` and `left`.

(`type:` could be `state:` as well, don't really care about the specific name(s) that much. `joined` could be `entered`, etc.)

**Name** for this new rpc: `room.attendants`

updates #89

**Comment by staltz** [comment]
Yes, I'm favorable of this, but I think there's something missing: how would the client know what is the initial state? Is there a separate API to call to get the initial state?

E.g. suppose the current state of attendants is `[A,B,C]` and then D joins, and then E joins. When D joins, they'll subscribe to `room.attendants` and they'll be notified `{type: 'joined', id: E}`, but it's missing A, B, C. Have you thought about this? I had some thoughts but haven't found a way that's resistant against race conditions (subscribing too slow to the updates).

**Comment by staltz** [comment]
One idea: the first event emitted on `room.attendants` (`source` muxrpc I suppose) is the initial state, e.g. `{type: "state", [idA, idB, idC]}` and subsequent emissions are `type: joined` or `type: left`.

**Comment by cryptix** [comment]
Oh, totally right! I didn't mention initial state at all... :see_no_evil: 

+1to your suggestion to emit it once in the beginning!

**Comment by staltz** [comment]
Good, so here's how it would look like (and I might try implementing it in ssb-room-client already):

- Name: `room.attendants`
- Type: `source`
- Data: 
  1. Initial state `{"type":"state","ids":[A,B,C]}`
  2. Update
    - `{"type":"joined","id":D}`
    - `{"type":"left","id":B}`

**Comment by cryptix** [comment]
I feel like we are in a good place here and will implement this now.
