### ISSUE TITLE
Support checking passwords against haveibeenpwnd

### ISSUE THREAD

**Issue by cryptix** [ssb-ngi-pointer/go-ssb-room#116]
during our demo yesterday @arj03 raised the concern that fallback passwords might be brute-forced by some means.

While we do have rate-limiting already, stuffing of leaked passwords is a valid concern still. Therefore, once users can update and reset their own passwords we probably want to add support for the Pwned passwords lookup: https://haveibeenpwned.com/API/v2#PwnedPasswords

tl;dr: you hash the new password of your user, send them a prefix of the hash and the result is all the matches of known passwords and the room can then check if the rest of the hash is in the list of returned values.

**Comment by cryptix** [comment]
Probably will use https://github.com/mattevans/pwned-passwords for this.

**Comment by decentral1se** [comment]
afaui this is done already? super nice feature.
