### ISSUE TITLE
Dashboard layout seems broken

### ISSUE THREAD

**Issue by cryptix** [ssb-ngi-pointer/go-ssb-room#119]
#107 somehow doesn't work like the PR screenshots looked for me.

I fixed one missing `</div>` in https://github.com/ssb-ngi-pointer/go-ssb-room/commit/1b3b13c885e308021627b6f2e36fa0b1626ca25e but there seems to be more and I don't understand flexbox enough to know what to poke at... :see_no_evil: 

<img width="1111" alt="Screenshot 2021-04-06 at 17 45 06" src="https://user-images.githubusercontent.com/111202/113739273-ec498480-96ff-11eb-9218-10080ffd72af.png">

**Comment by staltz** [comment]
Yes! I saw the same, i figured it out, it's just one closing div broken `</iv>`
