### ISSUE TITLE
Database model for privacy modes

### ISSUE THREAD

**Issue by staltz** [ssb-ngi-pointer/go-ssb-room#12]

**Comment by cryptix** [comment]
A bit meta but I'm having trouble making up my mind about this: I'm contested between have a separate config file that needs to be set before starting the server and putting it on a single row config table that can be changed from the web UI.

I see _being able to change from the frontend_ both as problem and feature here. Like, the HTTPS hostname is something we probably need before we could even show a first-use setup wizard.

Also _only_ being able to change it through the UI might also turn into a problem.

**Comment by cryptix** [comment]
We at least need to be careful not to mix deployment with room configuration.

If we advise for restoring from backup by just saving the roomdb, changing the hostname of your room might turn into a problem.

**Comment by staltz** [comment]
Hmm, I understand some of the problems you described, like the backup issue, but what's the connection between a privacy mode and the HTTPS hostname? Ideally it would be best that the privacy mode can be changed after deployment.
