### ISSUE TITLE
Server-initiated ssb-http-auth JS and SSE hiccups

### ISSUE THREAD

**Issue by staltz** [ssb-ngi-pointer/go-ssb-room#131]
On mobile, server-initiated ssb-http-auth works, but it's a bit fragile (sometimes works, sometimes needs a manual page refresh). I think that's because on mobile there is basically just one app "open and visible" at any single time, so once the browser switches to manyverse, maybe some logic on the browser goes to sleep, maybe it's some JS, maybe it's some SSE, I'm not sure. So when the user returns to the browser app, nothing happened (the page was not automatically redirected to the logged-in view, even though the muxrpc part of ssb-http-auth succeeded normally).

But we can probably fix this by doing some light JS on the server's page, where we listen to "window refocused" or something like that, to update state and do the redirect.

**Comment by cryptix** [comment]
We just need to make sure the browser stays on the same session token.

Maybe it's enough to reconnect the SEE client when the browser is back in focus?

**Comment by staltz** [comment]
I tried to fix this one in various ways but I got messed up with the Go channels and the SSE sending part, and the JS, and nothing I did made it better. Maybe @cryptix could try later, I could help you with reproduction steps (since they may only happen on Android Firefox).

Here's what I learned so far: 

- Android Firefox opens the server-initiated URL
- User presses the green button, it opens Manyverse, and Manyverse successfully calls the muxrpc
- The room server's log say it redirected to the signed-in landing page (see logs below)
- :bug: But Android Firefox still shows the server-initiated page
- :upside_down_face: But if you **tap** the address bar, the page suddenly changes (maybe it was just a visual glitch in Android Firefox then?)

```
level=debug package=web event=rendered tpl=auth/decide_method.tmpl status=200 took=1.06925ms size=4590
level=debug package=web event=rendered tpl=auth/withssb_server_start.tmpl status=200 took=1.654838ms size=5549
level=debug package=web urlPath=/withssb/events stream=MLF62 event="stream opened"
level=debug package=web urlPath=/withssb/events stream=MLF62 event="sent ping"
level=debug package=web urlPath=/withssb/events stream=MLF62 event="sent ping"
level=debug unit=tunnel called=isRoom
level=debug package=web urlPath=/withssb/events stream=MLF62 event=sent worked=true
level=debug unit=tunnel called=endpoints
level=debug package=web event=rendered tpl=landing/index.tmpl status=200 took=1.590028ms size=6998
```

**Comment by staltz** [comment]
Neverminddddd, check PR https://github.com/ssb-ngi-pointer/go-ssb-room/pull/136
