### ISSUE TITLE
ssb-http-auth QR Code should contain URL

### ISSUE THREAD

**Issue by staltz** [ssb-ngi-pointer/go-ssb-room#132]
I tested the ssb-http-auth server-initiated QR code in 3 popular QR code scanner apps on Android and they didn't work (well, they correctly detected the contents of the QR to be the SSB URI, but they didn't attempt to open the SSB URI using a compatible app), so it seems they'll be useless like that.

We could change the contents of the QR code to be *current URL*, which means that once scanned, the scanner app would redirect to the browser *on the phone*, which is different than what we we're aiming at with these QR codes (we wanted to login on desktop using mobile SSB ID), but at least it will successfully login on mobile, instead of just showing you the SSB URI as raw text, which is not really useful to an end-user if they can't "activate" that.

**Comment by cryptix** [comment]
Agreed. It's not super nice (would be cool if it were totally local) but since we need this to work in all cases/platforms and we also require network connectivity anyhow (since it's for http auth over the internet, duh..) the proposed solution seems fine to me.

**Comment by staltz** [comment]
I thought about this over night and we could have the QR code contain a URL to a new route, and this new route would preserve the `sc` and would not have SSE. 

So the flow would be: desktop server-initiated page => QR scan on mobile => mobile browser opens new route page => press button on that page triggers the SSB URI on manyverse => ssb-http-auth muxrpc calls => desktop page gets the SSE event and proceeds successfully.

What do you think?

**Comment by cryptix** [comment]
> What do you think?

yup! sounds like a good work around for the problem :)

**Comment by staltz** [comment]
HA! I implemented this and when it works it's so seamless and beautiful. :)
