### ISSUE TITLE
Change privacy modes form ui depending on user role

### ISSUE THREAD

**Issue by cblgh** [ssb-ngi-pointer/go-ssb-room#138]
When https://github.com/ssb-ngi-pointer/go-ssb-room/tree/wip/privacy-checks lands, use one of its template helpers to:
* check if the current user is an admin
* if user is not an admin, change the privacy modes form from the summary/details hack to a disabled input :)

**Comment by staltz** [comment]
#150 might be a duplicate of this. @cblgh what do you think?

**Comment by cblgh** [comment]
@staltz 👍 #150 is a duplicate. wasn't sure if your mentions of privacy modes being lacking was in reference to tasks other than updating the ui :)

**Comment by staltz** [comment]
Thanks!
