### ISSUE TITLE
Common web security practicies

### ISSUE THREAD

**Issue by cryptix** [ssb-ngi-pointer/go-ssb-room#14]
* [x] CSRF via [gorilla/csrf](github.com/gorilla/csrf/)
* [x] Content Security Policy (CSP)
* [ ] Cross-Origin Resource Sharing (CORS)

**Comment by cryptix** [comment]
Probably also https://github.com/unrolled/secure for HTTPS enforcement

**Comment by cryptix** [comment]
Since this will also involve some API requests, another thing to add is [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS).

**Comment by cryptix** [comment]
Whops.. had a `fixes ...` somewhere.

**Comment by cryptix** [comment]
Closing this since I don't think we will need CORS right now.

Could be needed if alias resolving would happen in ssb-browser but we can re-open that once this is happening, I think.

**Comment by rmdes** [comment]
I'm getting CORS error that I would like to know if it's something I can fix on my side or it's related to this issue . 

This patchfox dev connecting to a Go-SSB-ROOM (dockerized) server from Patchfox

![image](https://user-images.githubusercontent.com/12155003/155370391-824283ef-b4c8-444c-b447-0bcec558b426.png)
