### ISSUE TITLE
Source nicer favicon

### ISSUE THREAD

**Issue by cblgh** [ssb-ngi-pointer/go-ssb-room#142]
This military-green-hermies-on-a-white-square-bg isn't really doing it for me
![2021-04-13-105104_25x19_scrot](https://user-images.githubusercontent.com/3862362/114525150-26f27600-9c46-11eb-921f-e99fee1aca56.png)

**Comment by cblgh** [comment]
a better favicon, tho i don't have the tooling in place to generate all of the alternate assets available under `web/assets/favicon`. do you @staltz? 

![image](https://user-images.githubusercontent.com/3862362/117975986-8d46e300-b32f-11eb-839a-d03f8df7fc33.png)

**Comment by staltz** [comment]
@cblgh It was @cryptix who made that favicon.

In the past in other contexts I think I've used some web tool to generate a bunch of favicons, I think. Or was it Sketch.app's own thing, I don't know.

**Comment by cblgh** [comment]
i've just used the same png asset and it tends to work ^^

**Comment by cryptix** [comment]
I used https://favicon.io/favicon-converter as the comment in the base.tmpl indicates ;)

**Comment by cblgh** [comment]
@cryptix ah :) i actually used the same one but by mistake x)

here's a screenshot of how it looks deployed, not really the best fit, but a step up from the military crab??
![2021-05-12-145126_346x174_scrot](https://user-images.githubusercontent.com/3862362/117978006-aea8ce80-b331-11eb-9f92-1ddb92cd0999.png)

commit & pr or nae?

**Comment by staltz** [comment]
Too blurry. I think the downsampling that these converters use is bilinear (if I remember correctly).

**Comment by cblgh** [comment]
riprip

**Comment by cblgh** [comment]
well i'll leave the PR open & let @staltz source a better one x)
