### ISSUE TITLE
registerAlias should return wildcard subdomain URL

### ISSUE THREAD

**Issue by staltz** [ssb-ngi-pointer/go-ssb-room#160]
Tangentially related to #152, we need the Go server itself to understand that wildcard subdomains are enabled, because `room.registerAlias` should return the alias URL in the format of `alice.room.com` if wildcard subdomains are used by the room.

A bare minimum solution is to have a CLI argument like `-wildcardaliases` which then informs the implementation that it can concatenate `Alias.Name` with `h.roomDomain` to create `alice.room.com`, instead of `router.CompleteAliasResolve`.

But we can consider other more elegant solutions.

The importance of `room.registerAlias` returning the subdomain is that this will be used by client applications to publish an about msg on SSB self-declaring their alias URL. Client apps can't independently guess what their alias URL is (concatenating the input name plus the multiserver address's host part) because not all rooms will support subdomains, so instead of the client apps doing guess work, the muxrpc should answer what is the truth.

**Comment by cryptix** [comment]
> But we can consider other more elegant solutions. 

I'd say we should have this on the settings page just like the default language. I'd just wait for #143 to go through first while I lay some groundwork in #162.

**Comment by staltz** [comment]
@cryptix Yes, Settings page would be decent for this!
