### ISSUE TITLE
Hosting documentation: using aliases-as-subdomains

### ISSUE THREAD

**Issue by staltz** [ssb-ngi-pointer/go-ssb-room#168]
This issue may overlap with #117, but at least this one means that hosting documentation has to explain about the `-aliases-as-subdomains` flag and when to use it.

**Comment by staltz** [comment]
@cryptix What do you think if we demote this to [Community launch](https://github.com/ssb-ngi-pointer/go-ssb-room/milestone/2)? It doesn't sound like a must-do before NGIP milestone meeting.

**Comment by cryptix** [comment]
yes, agreed!
