### ISSUE TITLE
Invite response should inform what features the room supports

### ISSUE THREAD

**Issue by staltz** [ssb-ngi-pointer/go-ssb-room#169]
@cryptix This is the "tiny change" I mentioned in our weekly meeting.

### Context

Restricted mode doesn't support aliases, which means clients should not call `room.registerAlias` because it will fail. Instead of letting clients do "trial and error", we could signal which features are available upon claiming the invite.

This has some overlap with muxrpc bootstrapping, but not entirely. Features on the server are not only which muxrpc APIs it supports, but also other things such as replication (signalling that the server is a pub) and others (thinking out loud: i18n, subdomain aliases or not, etc).

Also, if anyone wants to fork go-ssb-room and make go-ssb-pub, then these feature flags could help SSB apps detect that it's not a room (as opposed to assuming that HTTP invites *necessarily mean* a room 2.0). Contrast that with [ssb-room](https://github.com/staltz/ssb-room)'s style of having a hard-coded seed.

### Proposal

When POST request to claim the invite responds, its JSON body is 

```json
{
  "multiserverAddress": "${roomMsAddr}"
}
```

This issue is about changing that JSON response to be

```json
{
  "multiserverAddress": "${roomMsAddr}",
  "features": [
    "feature1",
    "feature2",
    "feature3"
  ]
}
```

### Example

JSON response

```json
{
  "multiserverAddress": "net:scuttlebutt.eu:8008~shs:zz+n7zuFc4wofIgKeEpXgB+/XQZB43Xj2rrWyD0QM2M=",
  "features": [
    "tunnel",
    "room1",
    "room2",
    "alias",
    "httpAuth"
  ]
}
```

The specific strings that can be included in `features` is still up for debate, but here's a sketch:

- `"tunnel"`: the server supports muxrpc APIs such as `tunnel.connect`
- `"room1"`: the server supports extra tunnel APIs `tunnel.endpoints` and `tunnel.isRoom`
- `"room2"`: the server supports muxrpc APIs such as `room.attendants`
- `"alias"`: the server supports alias registration and revocation
- `"httpAuth"`: the server supports sign-in with ssb

The meanings of these strings can be put up on a spec doc dedicated to HTTP invites.

### Implementation

Note I put this under milestone "Community launch". I don't think we need it for NGIP. Implementation should be rather simple, as far as I see, may vary internally in the Go codebase (some configs are simple to detect, others configs may take some more plumbing effort to plug, and some feature strings can be hard-coded since they will be always present in go-ssb-room such as `"tunnel"`).

**Comment by cryptix** [comment]
I like the idea in general but I think a better place for this might `room.metadata` since stuff might change after an invite is claimed.

**Comment by staltz** [comment]
Cool, so let's close this issue in favor of `room.metadata` containing those information. #89
