### ISSUE TITLE
Make sure disconnected SSB peers are removed from the room state

### ISSUE THREAD

**Issue by cryptix** [ssb-ngi-pointer/go-ssb-room#173]
See #172

**Comment by cryptix** [comment]
There was code which removed peers who couldn't be connected but it led to false positives and needs to differentiate _no, i dont want to_ from actual transport errors.

I have a better method in mind for this then using the errors from the tunnel.connect call from room to target, tho.

**Comment by staltz** [comment]
Supposing tunnel.connect, Stranger==>Room==>Member, what do you think if Stranger gets the error "could not connect to Member" for *both* cases where Member is offline and when Member is online but doesn't want Stranger. My thinking is that plausible deniability could shield Member from Stranger using tunnel.connect to spy on the dates and time when Member is online.

**Comment by cryptix** [comment]
That's a good suggestion and it would fix #154 in one swoop but it's more concerned with connection establishment then _who appears online_, no?

This issue is supposed to be about which peers show up in tunnel.endpoints and the dashboard.

**Comment by staltz** [comment]
Ah right, no problem, I think i misunderstood your previous comment. Proceed as planned :)
