### ISSUE TITLE
JSON alias endpoint not working

### ISSUE THREAD

**Issue by staltz** [ssb-ngi-pointer/go-ssb-room#181]
This one is easy to test: open this URL https://staltzphone.hermies.club?encoding=json and it should respond with a JSON body.

**Comment by cryptix** [comment]
ouch. This slipped through #117 - the alias forwarding wrongly strips the rest of the url

**Comment by cryptix** [comment]
Fixed on the demo server, updating config here now.

**Comment by staltz** [comment]
Good! Just one more detail until ssb-room-client consumeAlias works with `alice.room.com`: #183
