### ISSUE TITLE
Verify all elevated request handlers properly guard against unelevated users

### ISSUE THREAD

**Issue by cblgh** [ssb-ngi-pointer/go-ssb-room#185]
Currently, we have a combination of elevated routes (routes that perform changes in the database && which only certain user roles should be allowed to perform) that check the requester's user role before processing, and routes which do not perform any checks. This issue tracks which routes should be patched, and whether they have been patched.

> **Note** Inclusion in the list below does *not* mean that the route does not check roles, it means that it has not been verified to check roles (by me, when writing this issue). If you know that a route is missing, add it. If you know that a route does indeed check roles, tick the box.

Routes requiring authentication
* [x] /admin/alias/revoke
* [ ] /admin/denied
* [ ] /admin/denied/add
* [ ] /admin/denied/remove
* [ ] /admin/denied/remove/confirm
* [x] /admin/invites/create
* [ ] /admin/invites/revoke/confirm?id=z
* [ ] /admin/invites/revoke (type POST i believe)
* [ ] /admin/members
* [ ] /admin/member/remove?id=x
* [x] /admin/member change-role (dunno route)
* [ ] /admin/members/remove/confirm?id=y
* [ ] notice add
* [ ] notice edit
* [x] /admin/settings/set-privacy
* [x] /admin/settings/set-language

For more discussion see: https://github.com/ssb-ngi-pointer/go-ssb-room/pull/179#discussion_r617575579

**Comment by cryptix** [comment]
Thanks a lot for this overview.

This would also fix #176, right?

**Comment by cblgh** [comment]
Yes!

**Comment by cryptix** [comment]
Updated to reflect PR #200.
