### ISSUE TITLE
README features are out of date

### ISSUE THREAD

**Issue by cryptix** [ssb-ngi-pointer/go-ssb-room#186]
* Aliases are done
* Banned is a thing, too
* privacy mode management maybe?
* add header image
* mention docs folder

**Comment by cblgh** [comment]
how do youse @cryptix @staltz feel about adding some kinda image to the readme? and show off how pretty the dashboard is 💖 

we can hack the image embed by pasting an image into an issue (or a github wiki page) and then using the generated link on the readme (and get away with not having to add an image to the repo proper :)

**Comment by cryptix** [comment]
i wouldn't mind having `docs/screenshots/dashboard{1..n}.png` either.
