### ISSUE TITLE
Rework sign-in page to handle SSB URIs with JS

### ISSUE THREAD

**Issue by staltz** [ssb-ngi-pointer/go-ssb-room#189]
We learned how to handle SSB URI links better with JS when working on alias and invites, now we should revisit the sign-in page to avoid the `_target="blank"` (originally meant to support Firefox Desktop neatly) because it's annoying that it opens an extra tab.

**Comment by staltz** [comment]
I'm working on this and realized that the issue with Firefox is different on this page compared to the other pages, because here we use SSE. The issue with Firefox is that SSE gets closed as soon as we do `window.location.replace(ssbUri)`. Seems to be a behavior only in Firefox. I'm not sure what to do about it, I have tried a couple things but I can't workaround the SSE getting closed.

**Comment by cryptix** [comment]
fixed in #191
