### ISSUE TITLE
Alias registration muxrpc errors could be more clear

### ISSUE THREAD

**Issue by staltz** [ssb-ngi-pointer/go-ssb-room#194]
Instead of this:

```
{
  name: 'Error',
  message: 'registerAlias: could not register alias: transaction failed, rolling back: models: unable to insert into aliases: UNIQUE constraint failed: aliases.name',
  stack: ''
}
```

the client could receive something like `this alias is already taken`. Something that could be easier for apps to parse and then render an appropriate and localized popup on the UI.

Note, not high priority.

**Comment by cryptix** [comment]
This should be fairy simple, we do this in other places already (like with public_key for members).
