### ISSUE TITLE
Find a way to ignore modTime changes in generated assets

### ISSUE THREAD

**Issue by cryptix** [ssb-ngi-pointer/go-ssb-room#20]

**Comment by cryptix** [comment]
I remembered a very nice post on the scuttleverse, introducing _merge drivers_: `%+JOXuDsv2OGSK0m4Mbxvj8POt2lsc8Mtl0RmIUIWRI8=.sha256`.

They mainly pointed to [npm-merge-driver](https://www.npmjs.com/package/npm-merge-driver) for resolving package-lock.json conflicts but there is also much more general informatio out there like [this blog post titled custom git merge drivers](https://www.julianburr.de/til/custom-git-merge-drivers/).

I only skimmed it but I'm 90% sure it should be possible to ignore changes automatically where only modTime changed and changes to content and size take precedence.

In general these conflicts should be disregarded if there are no hard conflicts on the actual files that get embedded (`web/assets/*`, `web/templates/*`, `web/i18n/defaults/*` and `admindb/migrations/*`)

**Comment by staltz** [comment]
I can't remember at the moment: what was the reason why generated assets are in git?

**Comment by cryptix** [comment]
ps: I wouldn't do this work against shurcooL's vfsgen but the upcoming [go1.16 feature](https://tip.golang.org/doc/go1.16#library-embed).

**Comment by cryptix** [comment]
> what was the reason why generated assets are in git?

I prefer checking out and being able to build the software (i.e. just checking out a version).

I agree tho that it _could_ be a git post-checkout hook, if that exists but still... It feels like thin ice having to do it properly before building the server. Having to setup npm to build the styles framework is close to a deal breaker to me.

**Comment by staltz** [comment]
> I prefer checking out and being able to build the software

Isn't asset generation a part of 'building the software'? I understand git committed things to be source code, emphasis on the word source. Generated in git makes it harder to review, harder to merge generated asset conflicts.

**Comment by cryptix** [comment]
Interesting... 

> Isn't asset generation a part of 'building the software'

I don't agree. For me you can't build the software until you have all the code for it but I'm sure we can come up with a a way that works for both of us.

An alternative could be a release branch and making `-tags dev` the default. I'm just concerned about users running in this trap of building the software in an unexpected mode.

**Comment by staltz** [comment]
> For me you can't build the software until you have all the code for it

But we do have all the code, don't we? Assets can be generated from source code, so there is no code missing. What is the trouble of doing `go generate` then `go build`? Perhaps with a bash script? I don't see the difficulty with this.

**Comment by cryptix** [comment]
> I don't see the difficulty with this.

Like I said, there is none other then having to properly document all the needed tools to setup the generators (like npm for tailwind). Also it could be cumbersome or even unavailable to setup on some platforms, where the checked in generated code is a clear win and not just convenience.

**Comment by staltz** [comment]
> Also it could be cumbersome or even unavailable to setup on some platforms, where the checked in generated code is a clear win and not just convenience.

Have an example of such platform? Are you intending to use git as a distribution channel where all the files are ready for consumption? I was understanding git's role as covering only source code version control.

**Comment by cryptix** [comment]
>  I had to install Go 1.14 from the website.

:man_shrugging:. I just had to compile nodejs from source on my FreeBSD box.

I'd really prefer if we check in the latest production version of the style.css and not require people to install software that is not strictly needed, especially if you just want to use it, and not hack on it. Development requirements can be different and already are.

**Comment by cryptix** [comment]
I don't see this discussion going anywhere, honestly. It would be nice if you at least told me which you prefer:

a) Have a release branch where the generated code is checked in

b) always having to re-generate everything after a checkout

**Comment by staltz** [comment]
@cryptix Are (a) and (b) the only ones I can choose? I think the discussion is valuable to know what we expect. It seems like you expect the Git repo to be a distribution channel, e.g. you mentioned the FreeBSD box and the "if you want to use it, not hack on it". In my experience, Git repo is used only for hacking on projects, not for using projects. E.g. if my project is a JavaScript one, the repo is for developers who want to hack on it. For those who want to use it, there's npm. Or dockerhub (the case of ssb-room 1.0). This is relevant to our discussions on how to distribute go-ssb-room in things like debian packages. Maybe you want GitHub Releases? I see it being sensible that we could build everything in CI and publish tars or things like that on GH Releases.

**Comment by cryptix** [comment]
I just double checked and tried go1.16rc1, which has a [new embed feature](https://tip.golang.org/doc/go1.16#embed). It makes me uneasy but solves your concern.

The embedding happens at `go build` time and you don't check in generated code.

**Comment by staltz** [comment]
> Until that's released I'm fine with not checking in the code and requiring manual steps before `go build`ing the server.

Alongside this, if you still want git for distribution, I'm also fine with option A, release branches.
