### ISSUE TITLE
"flash" errors

### ISSUE THREAD

**Issue by cryptix** [ssb-ngi-pointer/go-ssb-room#23]
not in the sense of _adobe flash_ but a way to add error/validation messages to a page (like name taken or login incorrect).

Right now we just render an error page with a back button.

**Comment by cryptix** [comment]
Not sure if it's even needed at this stage but feels like a massive _quality of life_ improvement for users later.

**Comment by staltz** [comment]
Yes, I thought about this too, like if you input an incorrect SSB ID. Not a big priority, but a nice to have.
