### ISSUE TITLE
a member connected in FeedRef is not a "Member" in the system making the dashboard render a 404

### ISSUE THREAD

**Issue by HendrikPetertje** [ssb-ngi-pointer/go-ssb-room#236]
So My `onlinerefs []refs.FeedRef` in `web/handlers/admin/dashboard.go` has 2 users connected to it right now (i'll hide actual public keys as to not shame anyone):

["@publicKeyOne", "@publicKeyTwo"]

[On lines 57 to 65 in the same file](https://github.com/ssb-ngi-pointer/go-ssb-room/blob/master/web/handlers/admin/dashboard.go#L57-L65) we loop over all onlineRefs and fill a list called "onlineMembers".
Line 60 returns an error, somehow someone managed to delete their account, but their client kept connecting. so now they are no longer a member and thus

```
onlineMembers[i], err = h.dbs.Members.GetByFeed(ctx, ref)
```

Results in an error that is catched and dealt with on line 61.

I would like to show the dashboard without worrying about the unregistered online members (and I'm super rusty when it comes to GoLang) (and not having the server crash over it).

Is it possible to assign nil to that array somehow, continue the loop and then filter out all instances of nil (keeping a clean list in the end)?

**Comment by cryptix** [comment]
I think #238 should fix this.

What I'm not sure is why the server crashes, tho. It should just show an HTML error-page with code 500.

Could you share the output you are seeing from the process before it exists?

**Comment by cryptix** [comment]
(ps: to test the fix you _just_ need to check out the PR branch (`fix-non-member-on-dashboard`) and rebuild the server binary.)

**Comment by HendrikPetertje** [comment]
Sorry for my wording, yes it shows  a 404 "not found" error. 
I'll fix that in my description as to not make more confusion.

I pulled your fix-non-member-on-dashboard branch and it works like a charm
