### ISSUE TITLE
Entries on /admin/members can overflow the UI layout due to multiple aliases

### ISSUE THREAD

**Issue by gtim** [ssb-ngi-pointer/go-ssb-room#250]
On the Members page, having multiple aliases can make an entry overflow.

![image](https://user-images.githubusercontent.com/1546926/121424864-1a527b80-c972-11eb-82b4-f20bcee980d4.png)

I'd be happy to write a patch. Would you prefer truncating the alias list or expanding the entry?

**Comment by staltz** [comment]
Thanks for spotting this! Yes we'd prefer the latter: expanding the height of the list item. But the list item needs a minimum height (matching the same fixed height dimensions as today).
