### ISSUE TITLE
AliasResolutionInstruct missing in active.de.toml

### ISSUE THREAD

**Issue by pathab** [ssb-ngi-pointer/go-ssb-room#254]
If default language is German the alias page is empty and shouts an error: 

`alias-resolve render errr: render: template(alias.tmpl) execution failed: template: alias.tmpl:5:32: executing "content" at <i18n "AliasResolutionInstruct">: error calling i18n: i18n/error: failed to localize label AliasResolutionInstruct: message "AliasResolutionInstruct" not found in language "de"`

**Comment by cryptix** [comment]
Sorry you ran into this and thanks for reporting.

I plan to spend a day on the localization feature next week and this will surely be on the list of things.

**Comment by pathab** [comment]
Cool, thank you!

If you need more or better German translation, I can also help.

**Comment by cryptix** [comment]
Yes, feel free!

I know some of them are a bit goofy. See also: https://github.com/ssb-ngi-pointer/go-ssb-room/issues/83#issuecomment-854355457

**Comment by decentral1se** [comment]
Since https://github.com/ssb-ngi-pointer/go-ssb-room/pull/257#issuecomment-976465264 is merged, I think this can be closed?
