### ISSUE TITLE
Migrating from ssb-pub to go-ssb-room

### ISSUE THREAD

**Issue by sunjam** [ssb-ngi-pointer/go-ssb-room#255]
Hi, I'm looking for [documentation](https://github.com/ssb-ngi-pointer/go-ssb-room/tree/master/docs) on migrating from [ssb-pub](https://github.com/ahdinosaur/ssb-pub) to go-ssb-room

- Will migrating away from our current Pub server implementation mean we are no longer scuttling data for our Pub followers and friends as a room?
- Is migrating as simple as moving the data directory over?

**Comment by staltz** [comment]
Hi! 



> Will migrating away from our current Pub server implementation mean we are no longer scuttling data for our Pub followers and friends as a room?

Rooms are quite different to pubs. Rooms in themselves do not replicate any data at all. I recommend watching https://www.youtube.com/watch?v=W5p0y_MWwDE



> Is migrating as simple as moving the data directory over?

No, not at all

**Comment by sunjam** [comment]
Reason I'm asking is [ssb-pub](https://github.com/ahdinosaur/ssb-pub) has gone unmaintained and recommends admins migrate over to rooms.  Thanks for the video.
