### ISSUE TITLE
Expired TLS cert on https://hermies.club/

### ISSUE THREAD

**Issue by Powersource** [ssb-ngi-pointer/go-ssb-room#259]

**Comment by staltz** [comment]
SOLVEDDDDDDD

**Comment by cryptix** [comment]
Resolved. Thanks for letting us know!

We will set an alert for next time (begining of october).

Our setup sadly doesn't allow us to cronjob this because we manually need to update the DNS entry for the wildcard certificate.

**Comment by cryptix** [comment]
whops.. :sweat_smile:
