### ISSUE TITLE
Enable local connections

### ISSUE THREAD

**Issue by brunovianna** [ssb-ngi-pointer/go-ssb-room#277]
As discussed in the devdiary  - %Kn1yjgA8eXi9cusnp6jpApqk2R3wbYs3UzCl8YLSQpo=.sha256 - we're developing a local community server around ssb. This local network should continue to work even when cut off from the internet (or in places with no connectivity).  Go-room-ssb expects a proxy and the SSL security infrastructure. However, it would be nice to offer users local functionality based on insecure LAN ips or local DNS. 

I suppose this could be done with a flag like "--allow-insecure-domains" and by creating a alternative initialization of secureMiddleware in https://github.com/ssb-ngi-pointer/go-ssb-room/blob/f6fca892cee9c488f3ba38b5dfaba657545b0a89/cmd/server/main.go#L314

But I don't know if it might have other consequences.

**Comment by cryptix** [comment]
I must say, I'm not sure this is a good idea. Disabling security features is often abused (like, clicking away _annoying_ warnings).

May I ask: What you _actually_ want is for peers to connect directly to each other, no?

**Comment by brunovianna** [comment]
I would like to have the functionality of the room -- showing a nice list of users connected to it -- but in local networks. 

Usually manyverse/patchwork is already able to find peers in the local network.

**Comment by staltz** [comment]
It would be good to know more of the reason why you want this, maybe we uncover something not yet understood. I also think like cryptix does that this is a dangerous idea.

If all the peers are in the local network, why do you need a room? (A room's purpose is primarily to recreate the benefit of LAN discovery when there is **no common LAN** among the peers)

**Comment by brunovianna** [comment]
The idea is to provide a more transparent way to find  local peers, to facilitate adoption in places where people are used to fb, twitter etc. For me the idea of the neighbors showing up in local room list is more intuitive than having them show up as peers. 

But agreed, it won't improve the functionality of LAN peer discovery. Maybe what we are looking for is some kind of opt-in local listing of peers so people can see everyone who connected to the local pub/room (even when they're not online). We are also looking into [ssb-promiscous](https://github.com/gmarcos87/ssb-promiscuous/) as another approach.

So unless you may think of another approach based on rooms, I'll close the issue for now.
