### ISSUE TITLE
Issue connecting to room server

### ISSUE THREAD

**Issue by PrasannaVenkadesh** [ssb-ngi-pointer/go-ssb-room#279]
Room Server: go-ssb-room version 2.0
Android Version: 8 and 11
Manyverse Version: 0.2112.3-beta-googlePlay

Manyverse Android app consumed the invite code and the toast message said that the invite was successful, but the room server did not appear in the connections panel. Tried with mobile data, Internet over WiFi. None of them worked.

Members list in the room server shows their Identity.

The same peer was connected to the room before and we had exchanged feeds, they reinstalled the app with backup phrase, hence same identity. After which they did not see the room server, so I removed them from the room server and shared an invite. We repeated this multiple times and no luck.

Tried killing and opening the app again, restarting the phone. None helped.

**Comment by ksinica** [comment]
What is interesting, it works when using an older version of Metaverse:

- ``0.2112.3-beta-fdroid (114)`` - not working
- ``0.2111.11-beta-fdroid (113)`` - not working
- ``0.2111.5-beta-fdroid (112)`` - works!

**Comment by staltz** [comment]
Yeah this is an issue in Manyverse, not go-ssb-room. I already fixed it yesterday https://github.com/staltz/manyverse/commit/3b4fcc291833fcdf14c780b164987fad3cf44365 and I'll make a new manyverse release soon, today or tomorrow. Sorry y'all for the problem
