### ISSUE TITLE
Replace News with content fields that are editable by admins

### ISSUE THREAD

**Issue by staltz** [ssb-ngi-pointer/go-ssb-room#28]
Examples:

- Code of conduct
- Description
- Privacy policy

**Comment by cryptix** [comment]
The idea for _news_ was to let admins customize their page but staltz brought up a good point that there are other areas that need customization.

**Comment by cryptix** [comment]
Feature wise this is pretty clear to me. I will also try to support multiple languages per page.

Favorite question, though: What do we call this concept?

**Comment by staltz** [comment]
Pages? Posts? Notices? Documents?

My favorite is notice. Dictionary mentions: *A written or printed announcement*, and it's a word we don't use elsewhere.
