### ISSUE TITLE
Can you join multiple rooms? What happens when you post in multiverse then?

### ISSUE THREAD

**Issue by ruifortes** [ssb-ngi-pointer/go-ssb-room#295]
Again, sorry if I'm missing something but...
Considering I'm not that dumb and I'm still struggling to figure out the basic functionality this definitely UX issue.
Can someone point me to a non-technical documentation about this?
Thanks

**Comment by staltz** [comment]
Yes you can join multiple rooms. Best non-technical documentation would be this https://www.youtube.com/watch?v=W5p0y_MWwDE
