### ISSUE TITLE
How to insert users on prepackaged binaries

### ISSUE THREAD

**Issue by CyberPingU** [ssb-ngi-pointer/go-ssb-room#296]
As for title,
I used the deb release for go-ssb-room
How to I insert an admin user since the insert-user binary doesn't seem to exist?

**Comment by rmdes** [comment]
I just went through the steps and when the package is installed, the best is to simply
git clone this https://github.com/ssb-ngi-pointer/go-ssb-room or download the source code https://github.com/ssb-ngi-pointer/go-ssb-room/releases/tag/v2.0.6 and unzip it, go inside the directory from your terminal
you need to have Go properly installed (go env and go version should work)
and then
follow the instruction from here https://github.com/ssb-ngi-pointer/go-ssb-room/blob/master/docs/deployment.md#first-admin-user

you will have to go inside the cmd/ directory and do "go build" inside the insert-user directory.
once that is done simply copy paste the last command instruction ./add-user from ith your own SSB profile
and you will have your first admin user.

./insert-user -repo "/var/lib/go-ssb-room" "@YourSSBKEY"

You can repeat that command with other @ ssb ID for friends that you want to put as admin or moderator.

**Comment by CyberPingU** [comment]
Thanks rmdes, it actually worked!
Now I'm facing the problem that I don't get the username to log in (it just asks for password so I have no clue what login username to use), and then if I try to use the manyverse app (android / linux) it doesn't do anything (linux: manyverse opens but nothing happens when I say "yes open the link", android doesn't open the app at all).
Any further clue? At least how to create the username ...

**Comment by CyberPingU** [comment]
Ok everything worked (except the fact that the app is not opened). Thanks!
