### ISSUE TITLE
Accepting an invite when you're already a member

### ISSUE THREAD

**Issue by staltz** [ssb-ngi-pointer/go-ssb-room#299]
**Expected:** the invite is accepted (claimed and removed) and the usual responses are given to the client.

**Actual:** the invite is rejected. (Tested with Manyverse 0.2203.7)

cc @achou11

**Comment by cryptix** [comment]
This should be fairly simple patch, handling the error here:

https://github.com/ssb-ngi-pointer/go-ssb-room/blob/6f5edbaa438fe473cc865e283bb3fd32de231c44/roomdb/sqlite/invites.go#L132-L135

Just make sure it actually is the right error type:

https://github.com/ssb-ngi-pointer/go-ssb-room/blob/7b3a5852dafa98b071e26ffaea9ae453db222c11/roomdb/sqlite/members.go#L74

So basically changing the error above to something like this:

```go
var alreadyAdded roomdb.ErrAlreadyAdded
if errors.As(err, &alreadyAdded) && alreadyAdded.PubKey.Equal(newMember) {
  // it is fine to use an invite twice
} else {
  return err
}
```

plus adding a test of course.. 🙃
