### ISSUE TITLE
Active navigation element

### ISSUE THREAD

**Issue by cryptix** [ssb-ngi-pointer/go-ssb-room#33]
Right now the navigation is just a static list of tags.

We could invest a little time to make it a function that emits the list with the current page marked as _active_.

**Comment by staltz** [comment]
Yes I thought about that exactly. Is there any pointers you can give me into the Go code that is responsible for that part?

**Comment by cryptix** [comment]
I would add it as a _injector function_, which can look at `http.Request`:

https://github.com/ssb-ngi-pointer/go-ssb-room/blob/f392dfbcf3f44fa9c74aa03089c07ae2733624cf/web/handlers/http.go#L70

I would just let it iterate over a slice of RouteName/i18nLabel. Possibly two lists (one for logged in, one for guest) or add a `Authed bool` to the list.

**Comment by cryptix** [comment]
ps: The name _inject_ might be a bit weird and they have to return a function even if it has no arguments. Stemming from the fact that they get use as [FuncMap](https://pkg.go.dev/html/template#FuncMap) elements before the render call.

**Comment by staltz** [comment]
Does it make sense that inside an injector function I would get this as result?

```go
render.InjectTemplateFunc("current_page_is", func(r *http.Request) interface{} {
	println("req url is", r.URL.Path)
```

(terminal:)
```
req url is /members
```

The browser location was `http://localhost:3000/admin/members`.

**Comment by staltz** [comment]
Nevermind, ended up using `r.ResponseURI`. We can discuss whether that's the correct one in the PR.

**Comment by cryptix** [comment]
Ugh... Right, sorry.

This is a side-effect of the nested "sub section" router setup. See the stripped and added prefixes [here in web/router](https://github.com/ssb-ngi-pointer/go-ssb-room/blob/f392dfbcf3f44fa9c74aa03089c07ae2733624cf/web/router/complete.go#L20) and [here in the handler setup](https://github.com/ssb-ngi-pointer/go-ssb-room/blob/f392dfbcf3f44fa9c74aa03089c07ae2733624cf/web/handlers/news/app.go#L21). The idea is that each sub-package (admin, news, other apis etc) can be defined and tested independent of the rest of the page. The admin tests only use the [_admin_](https://github.com/ssb-ngi-pointer/go-ssb-room/blob/f392dfbcf3f44fa9c74aa03089c07ae2733624cf/web/handlers/admin/app_test.go#L43) router, where the `/admin` prefix is missing unless you start composing the [_complete_](https://github.com/ssb-ngi-pointer/go-ssb-room/blob/f392dfbcf3f44fa9c74aa03089c07ae2733624cf/web/handlers/http.go#L37) router. 

It felt like a good separation of concerns but unless we re-use parts in other projects this doesn't give us anything and it's hard to see the whole picture, like here. It also caused problem for the auth handling where I had to break the pattern so that the middleware registers correctly.

I feel like the sane thing is to take this pattern out and just have one big router. The other reason for this pattern from another project was an additional API server and client layer between the frontend render server(s), which also used the named routes for safty. I don't see the need for this here, which additionally reduces the need for this pattern.

**Comment by cryptix** [comment]
> ended up using r.ResponseURI

I guess you mean `RequestURI`. Seems like an okay workaround for now until we solve the above. You might need to `net/url.Parse()` it to get just the path portion without query parameters.
