### ISSUE TITLE
When to collapse the menu layout

### ISSUE THREAD

**Issue by cryptix** [ssb-ngi-pointer/go-ssb-room#34]
I'm not a super strong proponent of this but I sympathize with the gist of this article:

[Just because I have a vertical screen, doesn’t mean I’m on a phone!](https://shkspr.mobi/blog/2021/02/just-because-i-have-a-vertical-screen-doesnt-mean-im-on-a-phone/)

(I use slim column layouts on my wide screen a lot)

**Comment by staltz** [comment]
I don't understand, and I have a vertical screen. Can you clarify?

**Comment by cryptix** [comment]
Oh.. I thought I saw it differently on the screenshot you posted on #32.

I thought the list of menu items would switch to horizontal on slim layouts.

I have a hunch there will be more buttons and if it stays vertical there will be a lot of white-space to the right of the menu items.

**Comment by cryptix** [comment]
Also, I feel like it could switch to collapsed sooner but that might be preference.

**Comment by staltz** [comment]
So this issue is that on mobile (and slim) screens there should be menu items side-by-side, not vertically?

**Comment by staltz** [comment]
I guess this is closed?
