### ISSUE TITLE
Add basic tests for HTML interface for editing notices

### ISSUE THREAD

**Issue by cryptix** [ssb-ngi-pointer/go-ssb-room#44]
We should nail down the endpoints and query parameters of them.

The admin test suite for allow-list should give a good idea how this can be done. https://github.com/ssb-ngi-pointer/go-ssb-room/blob/f774817536669c4f2ce2fe356a172d047ef5e780/web/handlers/admin/allow_list_test.go#L109

Check that

* [x] admidb/sqlite: the default notices are present (`/notice?id=x` for different x's) 
* [x] web/handlers: the _edit_ buttons show for logged in admins
* [x] web/handlers/admin: the _edit_ form includes all the needed fields, for input=hidden and input=text
  * [x] for add translation (new)
  * [x] for edit (existing)
* [x] web/handlers/admin: the _save_ handlers refuse incomplete requests (all the params included)
* [x] web/handlers/admin: make sure the _save_ handler calls the mockdb  (CallCount and CallArgs)

**Comment by cblgh** [comment]
preemptively assigning myself to https://github.com/ssb-ngi-pointer/go-ssb-room/issues/44 & https://github.com/ssb-ngi-pointer/go-ssb-room/issues/46

will see which one i feel i can get more traction on :^)

**Comment by cblgh** [comment]
@cryptix 
>  the edit form includes all the needed fields, for input=hidden and input=text

Would you mind briefly & explicitly enumerating the needed fields/expected forms? Not really familiar with what's supposed to be included or not atm :)

**Comment by cblgh** [comment]
i'm... done? the onboarding is COMPLETE? hit me up with that review @cryptix lemme know where i have been lacking or misunderstood things
