### ISSUE TITLE
Make language picking possible

### ISSUE THREAD

**Issue by cryptix** [ssb-ngi-pointer/go-ssb-room#45]
There should be a way for visitors to pick their preferred language.

I think it would be okay to store these in the session cookie. This would use the `github.com/gorilla/sessions` store we already have here:

https://github.com/ssb-ngi-pointer/go-ssb-room/blob/f774817536669c4f2ce2fe356a172d047ef5e780/web/handlers/http.go#L114

Then [Get](https://pkg.go.dev/github.com/gorilla/sessions#CookieStore.Get) the session (where name might be `room-settings`) and retreiev/set a "langauge value" from `session.Values`. See [the package documentation](https://pkg.go.dev/github.com/gorilla/sessions#pkg-overview) for some gotchas and maybe our [auth package](https://github.com/cryptix/go/blob/eb625e0824c4572ba1c7e10251c61ba1e34731b6/http/auth/auth.go#L132) for a concrete example. 

* [x] add a `/change-language` endpoint which updates the session
* [x] load the session and get the language in the helper code of our `web/i18n` package

For reference & a good way to get started with cookies, cryptix recommends the pairing:
> Just the cookie store get/set/save in handlers/auth/withssb AuthenticateRequest/Logout

This is follow up 3) of PR #40.

**Comment by cryptix** [comment]
Followup to this would be default language for the whole room but that needs parts of #12 first (i.e. room-wide admin settings)

Another follow-up would be some kind of EU-standardized banner about the use of cookies in general. Since we don't have external cookies and just these functionality ones (no tracking) it should be super simple.

**Comment by cryptix** [comment]
Also briefly talked with @cblgh about the whole _who do you go from `Accept: en;q=0.7` to `en-GB or..?`_ and that whole kerfuffle. Default tables for this could also be part of this issue.

**Comment by staltz** [comment]
Another thing we could do is assume `en` for now and postpone i18n a bit, so that we can tackle the bigger sharks first. We can have a meeting to discuss what shall we'all focus on building next.

**Comment by cryptix** [comment]
>  assume en for now

Yup, I just thought this might a simple orthogonal thing to get aquainted with the code base and libraries. Which is why I mentioned the other tasks as _follow up_s.

**Comment by staltz** [comment]
Ah right, gotcha. :+1:

**Comment by cblgh** [comment]
![2021-04-13-115732_924x686_scrot](https://user-images.githubusercontent.com/3862362/114534583-738e7f00-9c4f-11eb-8170-ab58f87a76a8.png)
cc @staltz wdyt

**Comment by staltz** [comment]
@cblgh Can you simulate a larger list of languages, so we know what kind of layout changes happen? On the styling, maybe it could look a bit more like a dropdown, with borders and such, e.g. https://opencollective.com/ footer for inspiration, or the Privacy Mode style but "dimmed" a bit in colors (because the white background might contrast too strongly).

:)

**Comment by cblgh** [comment]
@staltz how about this?
![2021-04-13-135433_1830x950_scrot](https://user-images.githubusercontent.com/3862362/114548255-d2f48b00-9c5f-11eb-9ad9-bf6a511ffd24.png)
![2021-04-13-135440_1859x977_scrot](https://user-images.githubusercontent.com/3862362/114548259-d38d2180-9c5f-11eb-8a1d-5b1db217d85f.png)

**Comment by staltz** [comment]
Works! :)

**Comment by cblgh** [comment]
ok i think i landed on this now
![2021-04-13-163721_1316x1034_scrot](https://user-images.githubusercontent.com/3862362/114570959-8ff1e200-9c76-11eb-8c1a-8fe8deb93a1b.png)

![2021-04-13-163635_1309x1033_scrot](https://user-images.githubusercontent.com/3862362/114570834-72247d00-9c76-11eb-8a5c-cb011fdf8503.png)

**Comment by staltz** [comment]
Ship it!
