### ISSUE TITLE
Room metadata when peer calls isRoom()

### ISSUE THREAD

**Issue by staltz** [ssb-ngi-pointer/go-ssb-room#58]
**Actual response:** `boolean`

**Expected response:**

```
{
  name: 'hermies.club', // i.e. the room's host
  features: [
    'tunnel', 
    'room1',
    // 'room2', // once we have attendants() and metadata()
    'alias',
    'httpAuth',
    'httpInvite'
  ]
}
```

-------

From Wouter's [UX research](https://www.manyver.se/ux-research/):

> Another note for a server feature: in the design of the Join room server screen, I conceptualised a new feature for room servers. Where a room server admin could link their personal SSB account to the server. This is expected to increase trust for potential new users of this room server, because they can then see which person owns it. (See the notes in report 3)

Actually, room1 answers `rpc.tunnel.isRoom` with an object which gives metadata about the room:

https://github.com/staltz/ssb-room/blob/e78d54887682664def36d48ca9e648fc609478e9/tunnel/server.js#L71-L77

For room2, we could support the same, while also adding more metadata, such as the admin's feed id, and the moderators feed ids.

**Comment by cryptix** [comment]
@staltz Did I understand right you wanted to change the format a little more?

using the HTTPS Doman name for `name: ...` should be simple.

Wondering what description is used for. Quickest hack I could think of would maybe re-use one of the notices?

The `features: [ ... ]` could be hardcoded + looking at privacy mode, I assume?

**Comment by staltz** [comment]
One thing I realized is that we need a way to signal that the go-ssb-room is running in "room 1.0 mode" which means "Open mode" where that seed-based invite code should work.

So could we emit the `'room1'` string in the `features` array *only if* the mode is *Open*?

**Comment by cryptix** [comment]
Yea, that should be doable. We need to look at privacy mode anyhow to know if it should add `alias`.

**Comment by staltz** [comment]
Some updates to this, again. Sorry if I'm going back and forth, but as I'm implementing changes in ssb-room-client I discover some constraints or missing bits here and there. Here's my latest suggestion:

```js
{
  // i.e. the room's host
  "name": "hermies.club",
  
  // boolean indicating whether you are a member or not
  "member": true, 

  features: [
    "tunnel", 
    "room1", // if mode is Open
    "room2", // if attendants() and metadata() is supported
    "alias", // is mode is not Restricted
    "httpAuth",
    "httpInvite" 
  ]
}
```

The `member` field is necessary because when it's `false` it can mean either external user (consuming aliases, etc) **or** the peer was just recently excluded as a member. 

Contrast that with tracking it client-side. If the client accepted an invite, they became a member, and they can store a boolean in conn.json, but they cannot trust that they will always be a member, because they can get excluded by a mod. It's better if the client can get this info from the server. This way we don't need do trial-and-error registerAlias just to discover that we were excluded from the room.
