### ISSUE TITLE
No websocket support?

### ISSUE THREAD

**Issue by arj03** [ssb-ngi-pointer/go-ssb-room#67]
Wanted to try out devroom.mindeco.de but it appears that web sockets is not enabled, is that correct? I sneakily tried to just replace net with wss ;-)

**Comment by cryptix** [comment]
Yup, but that's mostly because the web/https proxy isn't setup right. The support is there, just like in go-ssb.

https://github.com/ssb-ngi-pointer/go-ssb-room/blob/bbcab73cb53a36e2258917fa7add9cf9eeae0a3a/internal/network/websocket.go#L18

**Comment by arj03** [comment]
Okay, just wanted to confirm. Was testing the new rooms client yesterday so thought it might be a good idea for me to be connected to the dev room as well :-)

**Comment by cryptix** [comment]
Actually I realized that this needs to be patched into the web server the room already has. Currently opens a 3rd.

Which then made me realize: there is no path on the multiserver address for the websocket... I would prefer we add one for easier routing. Like, not guessing if `/` is for the landing page or should be upgraded to websocket.

**Comment by cryptix** [comment]
I tried to look into the needed javascript change but got lost inbetween multiserver/transport stuff...

I would assume the path would go in here but I have no clue, really.

https://github.com/ssbc/ssb-ws/blob/c995b473e225546609e34982a51218e5b4f96fae/inject.js#L33


the assumption is that this is what get's passed to the transport client here:

https://github.com/ssb-js/multiserver/blob/e001cd13fe4ea6928dfd608bfaed770659ee4537/plugins/ws.js#L107

**Comment by arj03** [comment]
Can't we just use another port?

**Comment by cryptix** [comment]
:man_shrugging: I mean, I can also patch it into the index page handler. Not sure which is less of a hack.

A different port, sure. I personally would put it on a different sub-domain in the proxy that does the TLS certificate management anyhow. I was just thinking how we explain this to the end-users later but I guess _It's complicated_ is enough for a start.

**Comment by arj03** [comment]
Wup :)
