### ISSUE TITLE
Use new muxrpc namespace room.* and soft deprecate tunnel.*

### ISSUE THREAD

**Issue by staltz** [ssb-ngi-pointer/go-ssb-room#89]
- [x] Design/specify `room.metadata`
  - Should list which *features* the room supports, e.g. #169 
- [x] Design/specify `rooms.attendants`, an alternative to `tunnel.endpoints`
  - See #110 
- [x] Implement `room.metadata`
  - See #58 
- [x] Implement `room.attendants` alternative, #110
- [x] Mark `tunnel.endpoints` as deprecated but keep it working
- [x] Mark `tunnel.isRoom` as deprecated but keep it working
- [x] remove `room.announce` and `room.leave`
- [x] Update the rooms2 spec doc

**Comment by staltz** [comment]
> tunnel.endpoints alternative

Ideas:

- `room.crowd`
- `room.attendance`
- `room.attendants` (my favorite)
- `room.audience`
- `room.assemblage`

**Comment by cryptix** [comment]
`room.attendants` :+1: (had to look it up but contrary to my thoughts it translates to the german term for the right concept)

**Comment by staltz** [comment]
> Mark tunnel.isRoom as deprecated but keep it working
 
 is this done?

**Comment by cryptix** [comment]
See https://github.com/ssb-ngi-pointer/go-ssb-room/pull/220#issuecomment-842401241.

I wasn't sure if those deprecation comments were meant for the JS side. There isn't really a defined way to do deprecation in Go. You usually just remove the APIS from the next major version.

**Comment by staltz** [comment]
@cryptix does attendants include the client's ID too? It seems like it doesn't? That's fine if it's the case, it's just different from tunnel.endpoints and I'd need to know (also to update the spec).

**Comment by cryptix** [comment]
Sorry, I'm not following. Is the client the joining/parting room member or the room or..?

**Comment by staltz** [comment]
When Alice connects to the room and calls the `room.attendants()` stream, she gets `{type: "state", ids: [BOB, CARLA]}` not `{type: "state", ids: [ALICE, BOB, CARLA]}`.

**Comment by staltz** [comment]
spec update: https://github.com/ssb-ngi-pointer/rooms2/pull/43
